### ISSUE TITLE
[MP Blog] Announcing an update for the Eclipse MicroProfile Course Bundle 

### ISSUE THREAD

**Issue by rieckpil** [microprofile/microprofile-marketing#259] opened 2020-04-14 18:21 UTC
Hi all,

I've just updated my free Eclipse MicroProfile course bundle to now support the latest MicroProfile version and created a blog post to announce it: https://microprofile.io/?p=6534&preview=true

Kind regards,
Phil

**Comment by rstjames** [comment] 2020-04-14 18:41
Hi Phil.
I will take a look at the blog and put together a SM push this week

**Comment by aeiras** [comment] 2020-04-14 19:07
@rieckpil do you mean your e-book is now 3.3 updated?
if yes, then we need to update the current bi-monthly push with new design that says 3.3. and version 2. do confirm, i will recommend small adjustments to current media description but up to you to adjust it. Amazing turnaround.

**Comment by rieckpil** [comment] 2020-04-15 07:05
Thanks for your quick reply and help @rstjames and @aeiras.

Yes, the e-book is now 3.3 updated.

What about the following adjustment to the tweet?

> 
> #MicroservicesEnthusiasts, Philip Riecks @rieckpil updated the comprehensive & free Course Bundle (E-Book, Video Course, Cheat Sheet) to kickstart your #MicroProfile success using the latest MicroProfile version 3.3. LINK_HERE
> 
> #opensource #MicroProfileeBOOK

Looking forward to hearing your feedback

**Comment by aeiras** [comment] 2020-04-15 18:37
reads perfect! 

@rstjames confirmed that current e-book pushes need to be deleted and the updated version needs to be put forth. Say, until the end of Q3 this time around. 

my only addition to your description @rieckpil is to add before your name #MicroProfiler Philip...
@rstjames thanks for closing ticket and choosing to help once again upon ticket arrival. :)

**Comment by rstjames** [comment] 2020-04-16 12:56
@rieckpil 
I updated the top image for the blog. I suggest to set the blog post a bit differently and maybe post it as a normal blog post and have an solid overview what is in the bundle and put a link to it instead of the redirect set up on the MP site. I can set up the link as a big button so people dont miss it. This makes it a bit easier to host it on the MP site. 

Also why is your old post "pending" I would not change or mess this that link because if anyone sees an old tweet with the link you want them to still be able to get to your site not get a 404. Make sense? You can update your old blog post with a CTA saying it has been updated... just an idea. This could help with traffic to your site. 

If you agree please let me know when this is done and I will push it all out. 

![MicroProfile-Course-Bundle-Philip-Rieckes](https://user-images.githubusercontent.com/12132146/79458652-63b76d00-7ff2-11ea-8148-2543ed08ed19.png)

**Comment by rieckpil** [comment] 2020-04-16 17:56
Thanks for the ideas @rstjames. I'll update it and create a proper blog post on microprofile.io instead of the redirect link and ping you once it's ready 👍 

Which old post do you mean? The one with the re-direct link or **Tutorials on each Eclipse MicroProfile Specification**

I somehow can't edit my old posts:

![Screenshot 2020-04-16 at 19 54 07](https://user-images.githubusercontent.com/14176609/79489851-3d0e2c00-801c-11ea-9bae-017fda105f3d.png)

**Comment by rstjames** [comment] 2020-04-17 14:16
@rieckpil maybe easiest thing is to have your old blog redirect to you new blog post. Thoughts? 
If you think this works I will take care of this when you are done with the blog post.

**Comment by aeiras** [comment] 2020-04-17 14:48
Stand by & allow me to look into Wordpress with my admin access to find issue & fix it before adjusting 1st blog! 💛

**Comment by aeiras** [comment] 2020-04-17 17:47
> Thanks for the ideas @rstjames. I'll update it and create a proper blog post on microprofile.io instead of the redirect link and ping you once it's ready 👍
> 
> Which old post do you mean? The one with the re-direct link or **Tutorials on each Eclipse MicroProfile Specification**
> 
> I somehow can't edit my old posts:
> 
> ![Screenshot 2020-04-16 at 19 54 07](https://user-images.githubusercontent.com/14176609/79489851-3d0e2c00-801c-11ea-9bae-017fda105f3d.png)

@rieckpil, 

Your blog is no published and you & Ryan can adjust its header banner & content as stated on previews exchanges +1!

I finally understand what you meant by not being able to adjust your blog, I assume you meant you were not able to publish your blog. That is normal as only MP Editors can push content from contributors. 

Please note that this update is a continuation of the introduction of your valuable e-book, as such I have adjusted its title, see below. :) Super fun stuff to see such a force of nature with content update Phil. you rock!

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/10731224/79598326-9c118680-8098-11ea-9e89-10053b5311be.png">

**Comment by aeiras** [comment] 2020-04-17 17:48
@rstjames, 

Phil needs to adjust the content of the blog as you suggested, excellent feedback by the way. 

Could you help him get a nice blog banner too? awesomeness via open channels. #oss!

**Comment by rieckpil** [comment] 2020-04-20 08:49
thanks for publishing it @aeiras.

As it is now published I can't edit this post anymore (you see this in the screenshot I sent before - after publishing its read-only). I wanted to incorporate @rstjames feedback and changing the blog post from a link to post type while adjusting the content.

Can I send you the final version and you change the content & post-type for me @aeiras? 

Thanks in advance,
Phil

**Comment by rieckpil** [comment] 2020-04-20 09:09
The final content of the blog post could be something like:

The Eclipse MicroProfile Course Bundle contains the most comprehensive e-book and video course to start learning Eclipse MicroProfile. It covers all twelve Eclipse MicroProfile specifications with hands-on examples and is constantly updated with each new MicroProfile release.

Not only does it help MicroProfile newcomers, but it also helps seasoned Java EE and Jakarta EE developers to enrich their existing applications with missing cloud-native features.

While working with this Course Bundle, you’ll:

* get hands-on experience with each MicroProfile specification
* write cloud-native applications with ease
* learn how to add missing parts (e.g. Open API support, JWT Auth, Resiliency, etc.) to an existing Enterprise Java application

The Course Bundle was recently updated to now cover Eclipse MicroProfile 3.3. With this minor release, the e-book now covers:

* Eclipse MicroProfile Config 1.3
* Eclipse MicroProfile Fault Tolerance 2.1
* Eclipse MicroProfile Health 2.2
* Eclipse MicroProfile Metrics 2.3
* Eclipse MicroProfile Rest Client 1.4

For two new features of this MicroProfile 3.3 release (@SimplyTimed and CDI support in ClientHeadersFactory), there is now also a dedicated video course section available.

GET ACCESS TO IT HERE (CTA Button)

**Comment by rstjames** [comment] 2020-04-20 16:41
@phillip-kruger 
- Blog has been updated. Touched up the formate a little bit. 
-  Eclipse MicroProfile release 3.2 blog has a redirect to the new blog post. 

**Tweet:**
#MicroservicesEnthusiasts, Philip Riecks @rieckpil UPDATED the comprehensive & free Course Bundle (E-Book, Video Course, Cheat Sheet) to kickstart your #MicroProfile success using the latest @MicroProfileIO version 3.3. https://bit.ly/3bq6e5I

#opensource #MicroProfileeBOOK

I will push it on SM today if all looks good to you. Please Confirm.

**Comment by phillip-kruger** [comment] 2020-04-20 17:07
I think you mean other Phillip :)  @rieckpil  ^^^

**Comment by rieckpil** [comment] 2020-04-20 17:19
thanks for your effort @rstjames. Blog post looks great 👍 You can start tweeting, thank you very much 🙇‍♂️

**Comment by rstjames** [comment] 2020-04-21 14:25
@rieckpil all set.

**Closed as completed by rstjames** 2020-04-21 14:25 UTC
Labels: Help Wanted

**Comment by aeiras** [comment] 2020-08-07 15:38
Hola @rieckpil, 

Yesterday with @rstjames, we discovered an issue listed here that affects the media post on your e-book. https://github.com/eclipse/microprofile-marketing/issues/305

We have fixed the issue & your e-book will be once again published via the MP twitter media as it was done before. 

Thank you for being that amazing!

**Comment by rstjames** [comment] 2020-08-11 09:35
@aeiras @rieckpil All updated and scheduled to go out.

**Comment by aeiras** [comment] 2020-08-11 17:05
Amazing turnaround Ryan! you are AMAZING :) THANK YOU!
